basics/urls.py
# -*- coding: utf-8 -*
from __future__ import unicode_literals

from django.conf.urls import url
from views import *
#from basics.views import SearchAutocomplete

app_name = "basics"
urlpatterns = [
    url(r'^doc_index/',                 doc_index_view, name="document_index"),
    url(r'^speaker_index/',             speaker_index_view, name="speaker_index"),
    url(r'^party_index/',               party_index_view, name="party_index"),
    url(r'^function_index/',            function_index_view, name="function_index"),
    url(r'^document/(?P<id>[0-9]+)/',   document_view, name="document"),
    url(r'^speaker/(?P<id>[0-9]+)/',    speaker_view, name="speaker"),
    url(r'^function/(?P<id>[0-9]+)/',   function_view, name="function"),
    url(r'^party/(?P<id>[0-9]+)/',      party_view, name="party"),
    url(r'^statements_search/',         statements_search_view_cached, name="statements_search"),

    url(r'^user_handling/',             user_handling_view, name='user_handling'),

    url(r'^ajax/statements/?',          statements_only_search_view_cached, name="statements_only"),
    url(r'^search_autocomplete/$',       SearchAutocomplete.as_view(), name='search_autocomplete'),
]

federalday/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
#from basics.views import default_redirect

urlpatterns = [
    url(r'^admin/',  admin.site.urls),
    url(r'^basics/', include("basics.urls")),
    #url(r'^',        default_redirect)
]

basics/views.py
# -*- coding: utf-8 -*

from __future__ import unicode_literals

import datetime

from django.http import HttpResponse
from django.shortcuts import render, Http404
from django.utils.translation import ugettext_lazy as _

from models import *

from tools import bokehplot
from views_helper import (get_l_l_part_of_speech_freqs, color_search_words,
                          filter_statements, filter_statements_cached,
                          order_stmts_by_speaker_stmt_blocks, pos_freq_dic,
                          count_speaker_party_from_statements_cached,
                          get_date_counts_from_stmts, get_l_speaker_distances)
from dal import autocomplete


class SearchAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = PickleCache.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs


def doc_index_view(request):
    ctx = {
        "title": _("document index"),
        "documents": Document.objects.all(),
    }

    return render(request, "basics/document_index.html", ctx)


def user_handling_view(request):

    return render(request, "basics/user_handling.html")


def speaker_index_view(request):

    speakers = Speaker.objects.all().order_by("name")
    print 'got speakers'
    l_parl_secretaries = []
    l_federal_ministers = []
    l_parlamentarians = []
    l_else = []

    for speaker in speakers:
        # print speaker.function
        if u'Staatssekretär' in speaker.function.name:
            l_parl_secretaries.append(speaker)
        elif u'Bundesminister' in speaker.function.name:
            l_federal_ministers.append(speaker)
        elif 'Abgeordnet' in speaker.function.name:
            l_parlamentarians.append(speaker)
        else:
            l_else.append(speaker)

    ctx = {
        "title": _("speaker index"),
        "l_parl_secretaries": l_parl_secretaries,
        "l_federal_ministers": l_federal_ministers,
        "l_parlamentarians": l_parlamentarians,
        "l_else": l_else,
    }
    print('rendering')
    return render(request, "basics/speaker_index.html", ctx)


def party_index_view(request):
    ctx = {
        "title": _("party index"),
        "parties": Party.objects.all(),
    }

    return render(request, "basics/party_index.html", ctx)


def function_index_view(request):
    ctx = {
        "title": _("function index"),
        "functions": Function.objects.all().order_by("name"),
    }
    return render(request, "basics/function_index.html", ctx)


def document_view(request, id):
    try:
        doc = Document.objects.get(document_id=id)
    except Document.DoesNotExist:
        raise Http404

    stmts = RegularStatement.objects.filter(document=doc).order_by("order_id")

    l_speakers = list(set([stmt.speaker for stmt in stmts]))

    for index, speaker in enumerate(l_speakers):
        l_speakers[index] = [unicode(speaker), str(stmts.filter(speaker=speaker).count())]

    l_speakers = sorted(l_speakers)
    ctx = {
        "title": "Dokument %s / %s" % (doc.document_id, doc.date),
        "url": doc.url,
        "statements": stmts,
        "speakers": l_speakers,
    }

    return render(request, "basics/document.html", ctx)


def speaker_view(request, id):
    try:
        speaker = Speaker.objects.get(pk=id)
    except Speaker.DoesNotExist:
        raise Http404

    num_search_fields = 1
    search_fields = []
    for i in range(10):
        term = request.GET.get("word%s" % i, None)
        if term:
            num_search_fields = i+2
            search_fields.append(term)
        else:
            break

    l_no_shared_words_speaker, l_normalized_shares_parties = get_l_speaker_distances(speaker)
    print(l_no_shared_words_speaker)

    filters = {
        "speaker": speaker,
    }

    all_search_terms = []

    stmts, no_stmts, no_stmts_filtered, l_counts_words, l_l_part_of_speech_freqs, l_year_str_l_freqs_words, l_count_date_url, l_dates, l_counts, l_counts_sorted_by_year = filter_statements_cached(
        search_fields, filters, request, all_search_terms)

    #stmts, no_stmts, no_stmts_filtered, l_counts_words = filter_statements(search_fields, filters)

    #l_l_part_of_speech_freqs, l_year_str_l_freqs_words = get_l_l_part_of_speech_freqs(stmts, request)

    all_search_terms = []
    for field in search_fields:
        for term in field.split(','):
            all_search_terms.append(term)

    stmts = color_search_words(stmts, all_search_terms)

    stmt_group_number = 0
    last_order_id = 0
    last_date = ''
    number_of_active_dates = 0
    d_leg_period_no_stmts = {}
    d_leg_period_active_dates = {}
    if stmts.exists():

        for stmt in stmts:
            date = stmt.document.date
            leg_period = stmt.document.legislative_period
            if leg_period in d_leg_period_no_stmts:
                d_leg_period_no_stmts[leg_period] += 1
            else:
                d_leg_period_no_stmts[leg_period] = 1

            order_id = stmt.order_id
            if last_date == date:

                if order_id - last_order_id == 1:
                    stmt.group_number = stmt_group_number
            else:
                if last_date != date:
                    number_of_active_dates += 1
                if leg_period in d_leg_period_active_dates:
                    d_leg_period_active_dates[leg_period] += 1
                else:
                    d_leg_period_active_dates[leg_period] = 1
                last_date = date
                stmt_group_number += 1
                stmt.group_number = stmt_group_number
            last_order_id = order_id
        number_of_statements = stmts.count()
        first_date = stmts[0].document.date
    else:
        number_of_statements = 0
        first_date = "never"
        l_year_str_l_freqs_words = []

    l_leg_period_active_dates = sorted([[k, v] for k, v in d_leg_period_active_dates.iteritems()])
    l_leg_period_no_stmts = sorted([(k, v, d_leg_period_active_dates[k]) for k, v in d_leg_period_no_stmts.iteritems()])
    l_active_dates = [v for k, v in l_leg_period_active_dates]

    form = """<form name="word-search-form" method="GET">"""
    form += """<input type="submit" value="%s"/>""" % _("Suchen")
    for i in range(num_search_fields):
        val = request.GET.get("word%s" % i, "")
        form += """ <input type="text" name="word%s" placeholder="%s" value="%s"/>""" % (
            i, _("search word"), val)
    form += "</form>"

    ctx = {
        "title": "%s" % speaker,
        "form": form,
        "statements": stmts,
        "number_of_statements": number_of_statements,
        "number_of_statement_blocks": stmt_group_number,
        "first_date": first_date,
        "last_date": last_date,
        "number_of_active_dates": number_of_active_dates,
        "search_words": search_fields,
        "l_leg_period_no_stmts": l_leg_period_no_stmts,
        "l_active_dates": l_active_dates,
        "l_l_part_of_speech_freqs": l_l_part_of_speech_freqs,
        "l_counts_words": l_counts_words,
        "l_no_shared_words_speaker": l_no_shared_words_speaker,
        "l_normalized_shares_parties": l_normalized_shares_parties,
    }
    if search_fields:
        if not stmts:
            return render(request, "basics/speaker_filtered_word_not_found.html", ctx)
        return render(request, "basics/speaker_filtered.html", ctx)
    return render(request, "basics/speaker.html", ctx)


def statements_search_view(request):

    num_search_fields = 1
    search_fields = []
    for i in range(10):
        term = request.GET.get("word%s" % i, None)
        if term:
            num_search_fields = i+2
            search_fields.append(term)
        else:
            break

    filters = {}
    all_search_terms = []
    l_l_part_of_speech_freqs = []
    if search_fields:
        stmts, no_stmts, no_stmts_filtered = filter_statements(search_fields, filters)

        l_l_part_of_speech_freqs = get_l_l_part_of_speech_freqs(stmts, request)

        for field in search_fields:
            for term in field.split(','):
                all_search_terms.append(term)
        stmts = color_search_words(stmts, all_search_terms)
    else:
        stmts = None
        no_stmts_filtered = 0

    if stmts and stmts.exists():

        l_count_date = get_date_counts_from_stmts(stmts)
        print('counted dates')
        # number_of_statements = stmts.count()
        first_date = stmts[0].document.date
        last_date = stmts.reverse()[0].document.date
        speaker_ids = stmts.values_list('speaker')
        # print(speaker_ids)
        speaker_no_statements = {}

        for i in speaker_ids:
            the_id = i[0]
            speaker = Speaker.objects.get(pk=the_id)

            if speaker in speaker_no_statements:
                speaker_no_statements[speaker] += 1
            else:
                speaker_no_statements[speaker] = 1

        party_no_statements = {}
        for speaker in speaker_no_statements:
            party = speaker.party.abbrev
            if party in party_no_statements:
                party_no_statements[party] += speaker_no_statements[speaker]
            else:
                party_no_statements[party] = speaker_no_statements[speaker]

        url_search_words_add = request.get_full_path().split('/')[-1]

        d_speaker_counts = pos_freq_dic('speaker_stmt_count')
        # print d_speaker_counts

        l_stmts_no_speaker = sorted(
            [
                (
                    no_stmts, speaker.name,
                    speaker.link_decorator() + url_search_words_add,
                    speaker.function.name,
                    speaker.function.link_decorator() + url_search_words_add,
                    speaker.party.abbrev,
                    speaker.party.link_decorator() + url_search_words_add,
                    round(no_stmts / d_speaker_counts[unicode(speaker)] * 100, 1)
                ) for speaker, no_stmts in speaker_no_statements.iteritems()

basics/templates/basics/base.html
<!doctype html>
<html>
  <head>
      {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'basics/bokeh-0.12.5.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'basics/style.css' %}" />
    <meta charset="utf-8">
    <script type="text/javascript" src="{% static 'basics/bokeh-0.12.5.min.js' %}">
</script>
    <script type="text/javascript" src="{% static 'basics/jquery-3.2.1.min.js' %}">
</script>
    <script type="text/javascript" src="{% static 'basics/search_word_highlighting.js' %}">
</script>
    <script type="text/javascript" src="{% static 'basics/lazy-container.js' %}"></script>
    <title>{{ title }}</title>
    <!-- <meta name="description" content="Webpage for xxxx"> -->

  </head>


  <body>
  <div class="navbar">
    <a href="{% url 'basics:document_index' %}">documents</a>
    | <a href="{% url 'basics:speaker_index' %}">speakers</a> | <a href="{% url 'basics:party_index' %}">parties</a> | <a href="{% url 'basics:function_index' %}">functions</a> | <a href="{% url 'basics:statements_search' %}">statements_search</a>
  </div>


    <script>
      var url_lazy_content = "{% url 'basics:statements_only' %}";
    </script>

    <div class="header">
    {% block title %}<h2>{{ title }}</h2>{% endblock %}
    </div>

  {% block content %}
  {% endblock %}

  </body>
</html>

basics/templates/basics/document.html
{% extends "basics/base.html" %}

{% block title %}<a href="{{ url }}"><h2>{{ title }}</h2></a>{% endblock %}
{% block content %}

<div class="button">Click</div>

<div class="target"></div>

<table align="center">
    <tr>
        <th><strong>Sprecher in der Sitzung</strong></th>
        <th>Anzahl an Aussagen</th>
    </tr>
    {% for speaker, no_stmts in speakers %}
    <tr>
        <td>{{ speaker }}</td>
        <td class="number">{{ no_stmts }}</td>
    </tr>
    {% endfor %}

</table>

{% regroup statements by speaker as stmts_list %}

<ul class="a">
{% for stmts in stmts_list %}
    <h3><a href="{{ stmts.grouper.link_decorator }}">{{ stmts.grouper }}</a> </h3>
    <ul class="b">
        {% for stmt in stmts.list %}
          <li><strong>S.{{ stmt.page }}:</strong> {{ stmt.text }}</li><br>
        {% endfor %}

    </ul>

    {% endfor %}

</ul>


{% endblock %}

basics/templates/basics/document_index.html
{% extends "basics/base.html" %}

{% block content %}

<table border="1">
{% for d in documents %}
    <tr>
        <td>{{ d.date }}</td>
        <td>{{ d.legislative_period }}</td>
        <td><a href="{{ d.link_decorator }}">{{ d.document_id }}</a></td>
    </tr>

{% endfor %}
</table>

{% endblock %}

basics/templates/basics/function.html
{% extends "basics/base.html" %}

{% block content %}

{{ form|safe }}

<table class="statistics" align="center">
    <tr>
        <th class="table_title" colspan="2">Statistik</th>
    </tr>
    <tr>
        <td>Anzahl an Statements</td>
        <td class="number">{{ number_of_statements }}</td>
    </tr>
    <tr>
        <td>Anzahl an Aussageblöcken</td>
        <td class="number">{{ number_of_statement_blocks }}</td>
    </tr>
    <tr>
        <td>Aktiver Zeitraum</td>
        <td class="number">{{ first_date }} - {{ last_date }}</td>
    </tr>
    <tr>
        <td>Aktive Sitzungen</td>
        <td class="number">{{ number_of_active_dates }}</td>
    </tr>
</table>

<table align="center">
    <tr>
        <th class="table_title" colspan="2">Amtsinhaber</th>
    </tr>
    {% for speaker in l_speakers %}

        <tr>
            <td><a href="{{ speaker.link_decorator }}">{{ speaker.name }}</a></td>
        </tr>
    {% endfor %}
</table>

<div class="collapse_button"></div>


{% for part_of_speech, l_word_freq in l_l_part_of_speech_freqs %}

    <table class="inline">
        <tr>
            <th colspan="3">{{ part_of_speech }} Häufigkeiten</th>
        </tr>

        {% for rel_freq, abs_freq, word, further_search_link in l_word_freq %}
            {% if forloop.counter0 < 3 %}
            <tr>
                <td>{{ word }}</td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% else %}
            <tr class="hideable">
                <td>{{ word|safe }}</td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endfor %}

<ul class="a">
{% for speaker, l_stmt_blocks in l_speakers_block_nos_stmts %}
        <h3><a href="{{ speaker.link_decorator }}">{{ speaker.name }}</a></h3>

        <ul class="b">

            {% for stmt_block in l_stmt_blocks %}
                <h3 class="stmt_block_title"><a href="{{ stmt_block.0.document.url }}">{{ stmt_block.0.document }}</a></h3>
                {% for stmt in stmt_block %}
                    <li>S.{{ stmt.page }}: {{ stmt.text | safe}}</li><br>
                {% endfor %}
            {% endfor %}

        </ul>
{% endfor %}
</ul>

{% endblock %}

basics/templates/basics/function_filtered.html
{% extends "basics/base.html" %}

{% block content %}

{{ form|safe }}

<h3>Statistik gefiltert duch das Suchwort: {{ search_word }}</h3>
<ul>
    <li>Statements Anzahl: {{ no_of_stmts_filtered }} von {{ no_of_stmts }}</li>
    <li>Hat zu dem Thema gesprochen im Zeitraum von {{ first_date }} - {{ last_date }} in {{ number_of_active_dates }} Sitzungen</li>
</ul>

<div class="collapse_button"></div>

<table class="inline">
    <tr>
        <th>Suchtrefferwort</th>
        <th>Anzahl</th>
        <th>%</th>
    </tr>

    {% for count, rel_count, word in l_counts_words %}
        {% if forloop.counter0 < 3 %}
        <tr>
            <td>{{ word }}</td>
            <td class="number">{{ count }}</td>
            <td class="number">{{ rel_count }}</td>
        </tr>
        {% else %}
        <tr class="hideable">
            <td>{{ word }}</td>
            <td class="number">{{ count }}</td>
            <td class="number">{{ rel_count }}</td>
        </tr>
        {% endif %}
    {% endfor %}

{% for part_of_speech, l_word_freq in l_l_part_of_speech_freqs %}

    <table class="inline">
        <tr>
            <th colspan="3">{{ part_of_speech }} Häufigkeiten</th>
        </tr>

        {% for rel_freq, abs_freq, word in l_word_freq %}
            {% if forloop.counter0 < 3 %}
            <tr>
                <td>{{ word }}</td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% else %}
            <tr class="hideable">
                <td>{{ word }}</td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endfor %}

<ul class="a">
{% for speaker, l_stmt_blocks in l_speakers_block_nos_stmts %}
        <h3><a href="{{ speaker.link_decorator }}">{{ speaker.name }}</a></h3>

        <ul class="b">

            {% for stmt_block in l_stmt_blocks %}
                <h3 class="stmt_block_title"><a href="{{ stmt_block.0.document.url }}">{{ stmt_block.0.document }}</a></h3>
                {% for stmt in stmt_block %}
                    <li>S.{{ stmt.page }}: {{ stmt.text | safe }}</li><br>
                {% endfor %}
            {% endfor %}

        </ul>
{% endfor %}
</ul>

{% endblock %}

basics/templates/basics/function_index.html
{% extends "basics/base.html" %}

{% block content %}

<table border="1">
{% for s in functions %}
    <tr>
        <td><a href="{{ s.link_decorator }}">{{ s.name }}</a></td>
        <td>{{ s.num_statements_decorator }}</td>
    </tr>

{% endfor %}
</table>

{% endblock %}

basics/templates/basics/party.html
{% extends "basics/base.html" %}

{% block content %}

{{ form|safe }}

<table class="statistics" align="center">
    <tr>
        <th class="table_title" colspan="2">Statistik</th>
    </tr>
    <tr>
        <td>Anzahl an Statements</td>
        <td class="number">{{ number_of_statements }}</td>
    </tr>
    <tr>
        <td>Anzahl an Aussageblöcken</td>
        <td class="number">{{ number_of_statement_blocks }}</td>
    </tr>
    <tr>
        <td>Aktiver Zeitraum</td>
        <td class="number">{{ first_date }} - {{ last_date }}</td>
    </tr>
    <tr>
        <td>Aktive Sitzungen</td>
        <td class="number">{{ number_of_active_dates }}</td>
    </tr>
</table>

<div class="collapse_button"></div>

<table align="center">
    <tr>
        <th class="table_title" colspan="2">Abgeordnete</th>
    </tr>
    {% for speaker in l_speakers %}
        {% if forloop.counter0 < 3 %}
            <tr>
                <td><a href="{{ speaker.link_decorator }}">{{ speaker.name }}</a></td>
                <td>{{ speaker.number_of_statements_decorator }}</td>
            </tr>
        {% else %}
            <tr class="hideable">
                <td><a href="{{ speaker.link_decorator }}">{{ speaker.name }}</a></td>
                <td>{{ speaker.number_of_statements_decorator }}</td>
            </tr>
        {% endif %}
    {% endfor %}
</table>


<ul class="a">
{% for speaker, l_stmt_blocks in l_speakers_block_nos_stmts %}
        <h3><a href="{{ speaker.link_decorator }}">{{ speaker.name }}</a></h3>

        <ul class="b">

            {% for stmt_block in l_stmt_blocks %}
                <h3 class="stmt_block_title"><a href="{{ stmt_block.0.document.url }}">{{ stmt_block.0.document }}</a></h3>
                {% for stmt in stmt_block %}
                    <li>S.{{ stmt.page }}: {{ stmt.text }}</li><br>
                {% endfor %}
            {% endfor %}

        </ul>
{% endfor %}
</ul>

{% endblock %}

basics/templates/basics/party_filtered.html
{% extends "basics/base.html" %}

{% block content %}

{{ form|safe }}

<h3>Statistik gefiltert duch das Suchwort: {{ search_word }}</h3>
<ul>
    <li>Statements Anzahl: {{ no_of_stmts_filtered }} von {{ no_of_stmts }}</li>
    <li>Hat zu dem Thema gesprochen im Zeitraum von {{ first_date }} - {{ last_date }} in {{ number_of_active_dates }} Sitzungen</li>
</ul>

<div class="collapse_button"></div>

<table class="inline">
    <tr>
        <th>Suchtrefferwort</th>
        <th>Anzahl</th>
        <th>%</th>
    </tr>

    {% for count, rel_count, word in l_counts_words %}
        {% if forloop.counter0 < 3 %}
        <tr>
            <td>{{ word }}</td>
            <td class="number">{{ count }}</td>
            <td class="number">{{ rel_count }}</td>
        </tr>
        {% else %}
        <tr class="hideable">
            <td>{{ word }}</td>
            <td class="number">{{ count }}</td>
            <td class="number">{{ rel_count }}</td>
        </tr>
        {% endif %}
    {% endfor %}

{% for part_of_speech, l_word_freq in l_l_part_of_speech_freqs %}

    <table class="inline">
        <tr>
            <th colspan="3">{{ part_of_speech }} Häufigkeiten</th>
        </tr>

        {% for rel_freq, abs_freq, word, further_search_link_UNUSED in l_word_freq %}
            {% if forloop.counter0 < 3 %}
            <tr>
                <td>{{ word|safe }}</td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% else %}
            <tr class="hideable">
                <td>{{ word|safe }}</td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endfor %}

<ul class="a">
{% for speaker, l_stmt_blocks in l_speakers_block_nos_stmts %}
        <h3><a href="{{ speaker.link_decorator }}">{{ speaker.name }}</a></h3>

        <ul class="b">

            {% for stmt_block in l_stmt_blocks %}
                <h3 class="stmt_block_title"><a href="{{ stmt_block.0.document.url }}">{{ stmt_block.0.document }}</a></h3>
                {% for stmt in stmt_block %}
                    <li>S.{{ stmt.page }}: {{ stmt.text | safe }}</li><br>
                {% endfor %}
            {% endfor %}

        </ul>
{% endfor %}
</ul>

{% endblock %}

basics/templates/basics/party_index.html
{% extends "basics/base.html" %}

{% block content %}

<table border="1">
{% for s in parties %}
    <tr>
        <td><a href="{{ s.link_decorator }}">{{ s.abbrev }}</a></td>
        <td>{{ s.num_statements_decorator }}</td>
    </tr>

{% endfor %}
</table>

{% endblock %}

basics/templates/basics/speaker.html
{% extends "basics/base.html" %}

{% block content %}

{{ form|safe }}



<table align="center">
    <tr>
        <th class="table_title" colspan="2">Statistik</th>
    </tr>
    <tr>
        <td>Anzahl an Statements</td>
        <td class="number">{{ number_of_statements }}</td>
    </tr>
    <tr>
        <td>Anzahl an Aussageblöcken</td>
        <td class="number">{{ number_of_statement_blocks }}</td>
    </tr>
    {% for leg_period, no_stmts, no_active_dates in l_leg_period_no_stmts %}
        <tr>
            <td>Wahlperiode {{ leg_period }}</td>
            <td class="number">{{ no_stmts }} Aussagen in {{ no_active_dates }} Sitzungen</td>
        </tr>
    {% endfor %}
    <tr>
        <td>Aktiver Zeitraum</td>
        <td class="number">{{ first_date }} - {{ last_date }}</td>
    </tr>
    <tr>
        <td>Aktive Sitzungen</td>
        <td class="number">{{ number_of_active_dates }}</td>
    </tr>
</table>

<div class="collapse_button"></div>


<table class="inline">
    <tr>
        <th>Sprecher</th>
        <th>Anzahl gemeinsamer Worte</th>
    </tr>

    {% for no_shared_words, speaker in l_no_shared_words_speaker %}
        {% if forloop.counter0 < 3 %}
        <tr>
            <td>{{ speaker }}</td>
            <td class="number">{{ no_shared_words }}</td>
        </tr>
        {% else %}
        <tr>
            <td>{{ speaker }}</td>
            <td class="number">{{ no_shared_words }}</td>
        </tr>
        {% endif %}
    {% endfor %}
</table>

<table class="inline">
    <tr>
        <th>Partei</th>
        <th>%</th>
    </tr>
    {% for normalized_party_share_index, party in l_normalized_shares_parties %}
        <tr>
            <td>{{ party }}</td>
            <td class="number">{{ normalized_party_share_index }}</td>
        </tr>
    {% endfor %}
</table>


{% for part_of_speech, l_word_freq in l_l_part_of_speech_freqs %}

    <table class="inline">
        <tr>
            <th colspan="3">{{ part_of_speech }} Häufigkeiten</th>
        </tr>

        {% for rel_freq, abs_freq, word, further_search_link in l_word_freq %}
            {% if forloop.counter0 < 3 %}
            <tr>
                <td><a href = "{{ further_search_link }}">{{ word | safe }}</a></td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% else %}
            <tr class="hideable">
                <td><a href = "{{ further_search_link }}">{{ word | safe }}</a></td>
                <td class="number">{{ rel_freq }}</td>
                <td class="number">{{ abs_freq }}</td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endfor %}


{% regroup statements by group_number as stmts_list %}

<ul class="a">
{% for stmts in stmts_list %}
    <h3>{{ stmts.grouper }}. Aussagenblock <a href="{{ stmts.list.0.document.url }}">{{ stmts.list.0.document }}</a></h3>
    <ul class="b">
        {% for stmt in stmts.list %}
          <li>S.{{ stmt.page }}: {{ stmt.text }}</li><br>
        {% endfor %}
    </ul>
    {% endfor %}
</ul>

{% endblock %}

basics/templates/basics/speaker_filtered_word_not_found.html
{% extends "basics/base.html" %}

{% block content %}


{{ form|safe }}

<div class="word_not_found"><h2>Das Suchwort konnte nicht gefunden werden - zurück zur <a href="basics/speaker.html">Übersicht</a>!</h2></div>


{% endblock %}